resources:
  - name: dwpdigital-blackbox-exporter
    type: registry-image-resource
    source:
      repository: dwpdigital/blackbox-exporter
    check_every: 5m

  - name: ecr-dwpdigital-blackbox-exporter-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "blackbox-exporter"

  - name: ecr-dwpdigital-blackbox-exporter
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "blackbox-exporter"
      aws_role_arn: arn:aws:iam::((aws_account.management)):role/ci

jobs:
  - name: mirror-dwpdigital-blackbox-exporter-dev
    serial_groups: [blackbox-exporter]
    plan:
      - get: dwpdigital-blackbox-exporter
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-blackbox-exporter-dev
        params:
          image: "dwpdigital-blackbox-exporter/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-blackbox-exporter
    serial_groups: [blackbox-exporter]
    plan:
      - get: dwpdigital-blackbox-exporter
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-blackbox-exporter
        params:
          image: "dwpdigital-blackbox-exporter/image.tar"
        attempts: 3
