jobs:
  - name: blackbox-exporter-pr
    plan:
      - get: blackbox-exporter-pr
        trigger: true
        version: every
      - put: blackbox-exporter-pr
        params:
          path: blackbox-exporter-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          blackbox-exporter: blackbox-exporter-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          blackbox-exporter: blackbox-exporter-pr
        params:
          TF_WORKSPACE: "management"
          DETAILED_EXITCODE: ""
        on_failure:
          put: blackbox-exporter-pr
          params:
            path: blackbox-exporter-pr
            status: failure
        on_success:
          put: blackbox-exporter-pr
          params:
            path: blackbox-exporter-pr
            status: success
